apiVersion: v1
kind: Namespace
metadata:
  name: shopmindai
  labels:
    name: shopmindai
    istio-injection: enabled
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-quota
  namespace: shopmindai
spec:
  hard:
    requests.cpu: "1000"
    requests.memory: 2000Gi
    limits.cpu: "2000"
    limits.memory: 4000Gi
    persistentvolumeclaims: "100"
    services.loadbalancers: "10"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: resource-limits
  namespace: shopmindai
spec:
  limits:
  - max:
      cpu: "4"
      memory: 8Gi
    min:
      cpu: 50m
      memory: 64Mi
    default:
      cpu: 100m
      memory: 128Mi
    defaultRequest:
      cpu: 50m
      memory: 64Mi
    type: Container
  - max:
      storage: 100Gi
    type: PersistentVolumeClaim